name: Release .crx
on:
  push:
    tags:
      - v**
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Read package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Build
        run: |
          npm install
          npm run build
      - name: Pack .zip
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: 'dist'
          zipFilePath: 'wai-v${{ steps.package-version.outputs.current-version }}.zip'
      - name: Pack .crx
        uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: 'wai-v${{ steps.package-version.outputs.current-version }}.zip'
          crxFilePath: 'wai-v${{ steps.package-version.outputs.current-version }}.crx'
          privateKey: ${{ secrets.CRX_PRIVATE_KEY }}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: false
          files: |
            wai-v${{ steps.package-version.outputs.current-version }}.zip
            wai-v${{ steps.package-version.outputs.current-version }}.crx
      - name: Upload to Chrome Web Store
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          extension-id: ackimleclkemolnfcfajficenpbnaiba
          file-path: 'wai-v${{ steps.package-version.outputs.current-version }}.zip'
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          publish: false
